import { TableCellsIcon } from "@heroicons/react/24/outline"
import {
  ArchiveBoxArrowDownIcon,
  ArchiveBoxIcon,
  ArchiveBoxXMarkIcon,
  ArrowDownOnSquareIcon,
  ArrowUpOnSquareIcon,
  AcademicCapIcon,
  BanknotesIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingOfficeIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChartPieIcon,
  ChatBubbleLeftIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorArrowRippleIcon,
  FaceFrownIcon,
  FaceSmileIcon,
  FireIcon,
  FlagIcon,
  FolderIcon,
  FunnelIcon,
  GlobeAmericasIcon,
  HandRaisedIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  HeartIcon,
  MicrophoneIcon,
  MoonIcon,
  MusicalNoteIcon,
  PhotoIcon,
  PlayPauseIcon,
  PuzzlePieceIcon,
  RectangleGroupIcon,
  ScaleIcon,
  ScissorsIcon,
  StarIcon,
  SunIcon,
  RectangleStackIcon,
  WindowIcon,
  CircleStackIcon,
  BugAntIcon,
  CheckBadgeIcon,
  MapIcon,
  InboxIcon,
} from "@heroicons/react/24/solid"
import { ReactNode } from "react"

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const AllIcons: Record<string, (props: any) => ReactNode> = {
  TableCellsIcon,
  BookOpenIcon,
  FunnelIcon,
  CloudArrowUpIcon,
  RectangleGroupIcon,
  FolderIcon,
  AcademicCapIcon,
  BoltIcon,
  HeartIcon,
  StarIcon,
  FaceSmileIcon,
  FaceFrownIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  HandRaisedIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxXMarkIcon,
  ArchiveBoxIcon,
  ArrowDownOnSquareIcon,
  ArrowUpOnSquareIcon,
  PlayPauseIcon,
  CursorArrowRippleIcon,
  ChartBarSquareIcon,
  ChartBarIcon,
  ChartPieIcon,
  CalculatorIcon,
  CalendarIcon,
  ClockIcon,
  GlobeAmericasIcon,
  BanknotesIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyYenIcon,
  CurrencyRupeeIcon,
  CurrencyBangladeshiIcon,
  SunIcon,
  MoonIcon,
  BuildingOfficeIcon,
  CakeIcon,
  CameraIcon,
  FireIcon,
  FlagIcon,
  ChatBubbleLeftIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  PhotoIcon,
  PuzzlePieceIcon,
  ScaleIcon,
  ScissorsIcon,
  RectangleStackIcon,
  WindowIcon,
  CircleStackIcon,
  BugAntIcon,
  CheckBadgeIcon,
  MapIcon,
  InboxIcon,
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const IconPickerIcons: Record<string, (props: any) => ReactNode> = {
  // Row
  TableCellsIcon,
  BookOpenIcon,
  FunnelIcon,
  CloudArrowUpIcon,
  RectangleGroupIcon,
  AcademicCapIcon,
  BoltIcon,
  // Row
  HeartIcon,
  StarIcon,
  FaceSmileIcon,
  FaceFrownIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  HandRaisedIcon,
  // Row
  ArchiveBoxArrowDownIcon,
  ArchiveBoxXMarkIcon,
  ArchiveBoxIcon,
  ArrowDownOnSquareIcon,
  ArrowUpOnSquareIcon,
  PlayPauseIcon,
  CursorArrowRippleIcon,
  // Row
  ChartBarSquareIcon,
  ChartBarIcon,
  ChartPieIcon,
  CalculatorIcon,
  CalendarIcon,
  ClockIcon,
  GlobeAmericasIcon,
  // Row
  BanknotesIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyYenIcon,
  CurrencyRupeeIcon,
  CurrencyBangladeshiIcon,
  // Row
  SunIcon,
  MoonIcon,
  BuildingOfficeIcon,
  CakeIcon,
  CameraIcon,
  FireIcon,
  FlagIcon,
  // Row
  ChatBubbleLeftIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  PhotoIcon,
  PuzzlePieceIcon,
  ScaleIcon,
  ScissorsIcon,
  // Row
  RectangleStackIcon,
  WindowIcon,
  CircleStackIcon,
  BugAntIcon,
  CheckBadgeIcon,
  MapIcon,
  InboxIcon,
}

export default AllIcons
